let mercancia =
 
	[
		{
			"nombre":"tomate",
			"cantidad":0,
			"precio":1500,
			"img":"tomate.jpg",
			"id":0
		},
		{
			"nombre":"cebolla",
			"cantidad":0,
			"precio":1300,
			"img":"cebolla.jpg",
			"id":1			
		},
		{
			"nombre":"ajo",
			"cantidad":0,
			"precio":1000,
			"img":"ajo.jpg",
			"id":2	
		},
		{
			"nombre":"apio",
			"cantidad":0,
			"precio":1050,
			"img":"apio.jpg",
			"id":3	
		},
		{
			"nombre":"calabacin",
			"cantidad":0,
			"precio":870,
			"img":"calabacin.jpg",
			"id":4	
		},
		{
			"nombre":"maiz",
			"cantidad":0,
			"precio":1100,
			"img":"maiz.jpg",
			"id":5	
		},
		{
			"nombre":"papa",
			"cantidad":0,
			"precio":1320,
			"img":"papa.jpg",
			"id":6	
		},
		{
			"nombre":"pimiento",
			"cantidad":0,
			"precio":1400,
			"img":"pimiento.jpg",
			"id":7	
		},
		{
			"nombre":"zanahoria",
			"cantidad":0,
			"precio":1240,
			"img":"zanahoria.jpg",
			"id":8	
		},
		{
			"nombre":"lechuga",
			"cantidad":0,
			"precio":1540,
			"img":"lechuga.jpg",
			"id":9	
		},
		{
			"nombre":"coliflor",
			"cantidad":0,
			"precio":890,
			"img":"coliflor.jpg",
			"id":10	
		},
		{
			"nombre":"ahuyama",
			"cantidad":0,
			"precio":1270,
			"img":"ahuyama.jpg",
			"id":11
		},
		{
			"nombre":"puerro",
			"cantidad":0,
			"precio":1070,
			"img":"puerro.jpg",
			"id":12	
		},
		{
			"nombre":"berenjena",
			"cantidad":0,
			"precio":780,
			"img":"berenjena.jpg",
			"id":13	
		},
		{
			"nombre":"pepino",
			"cantidad":0,
			"precio":654,
			"img":"pepino.jpg",
			"id":14	
		},
		{
			"nombre":"aji",
			"cantidad":0,
			"precio":754,
			"img":"aji.jpg",
			"id":15	
		},
		{
			"nombre":"brocoli",
			"cantidad":0,
			"precio":654,
			"img":"brocoli.jpg",
			"id":16	
		}		

	]


